# Metadata
title: Android Code
author: Maciej Nowak
email: kontakt@androidcode.pl
description: >- # this means to ignore newlines until "baseurl:"
  Android online treasury knowledge.
keywords: "android, code, coding, programming, programer, java, kotlin, libraries, mobile"
baseurl: ""
url: ""
lang: "pl"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-paginate
  - jekyll-feed

# Pagination
paginate: 6
paginate_path: "blog/page:num/"

# Permalinks
permalink: /blog/:title/

# Include / Exclude
include: ['_pages']

# Compressing
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]