# Metadata
title: Android Code
author: Maciej Nowak
email: kontakt@androidcode.pl
description: >- # this means to ignore newlines until "baseurl:"
  TODO.
keywords: "android, code, coding, programming, programer, java, kotlin, libraries, mobile"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-paginate
  - jekyll-feed

# Pagination
paginate: 6
paginate_path: "blog/page:num/"

# Permalinks
permalink: /blog/:title/

# Include / Exclude
include: ['_pages']