# Metadata
title: Android Code
author: Maciej Nowak
email: kontakt@androidcode.pl
twitter: maciejnowa
github: android-code
baseurl: ""
url: ""

# Switches
lang: "en"
lang-enable: yes
share-enable: yes

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-paginate
  - jekyll-feed

# Pagination
paginate: 6
paginate_path: "blog/page:num/"

# Permalinks
permalink: /blog/:title/

# Include / Exclude
include: ['_pages']

# Compressing
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]