# Metadata
title: Android Code
author: Maciej Nowak
email: kontakt@androidcode.pl
github: android-code
baseurl: ""
url: "http://androidcode.pl"
ghpage: "https://android-code.github.io"

# Switches
lang: "pl"
lang-switch-enable: false
post-share-enable: true
post-controls-enable: true
category-posts-show-less-number: 5
category-posts-show-less-enable: true
social-links-enable: true

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-paginate
  - jekyll-feed

# Pagination
paginate: 6
paginate_path: "blog/:num/"

# Date
date_format: "%d %b %Y"

# Permalinks
permalink: /blog/:categories/:title/

# Include / Exclude
include: ['_pages']

# Compressing
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]